language: elixir
elixir:
  - 1.5.0
notifications:
  recipients:
    - theavitex@gmail.com
otp_release:
  - 18.2
env:
  - MIX_ENV=test
script:
  - mix do deps.get, compile
after_script:
  - mix deps.get --only docs 
  - MIX_ENV=docs mix inch.report
